openapi: 3.0.0
info:
  title: On Center API
  version: 1.0.0
  description: API for the On Center application
  contact:
    name: API Support
    email: support@oncenter.local

servers:
  - url: http://localhost:3000
    description: Development server

tags:
  - name: Banks
    description: Endpoints for managing banks

paths:
  /banks:
    $ref: './paths/banks.yml#/collection'
  /banks/{id}:
    $ref: './paths/banks.yml#/item'

components:
  schemas:
    Bank:
      $ref: './components/schemas/Bank.yml#/Bank'
    CreateBankDto:
      $ref: './components/schemas/Bank.yml#/CreateBankDto'
    UpdateBankDto:
      $ref: './components/schemas/Bank.yml#/UpdateBankDto'
