name: openapi-pull

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'openapi/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install CLI dependencies
        run: |
          npm install -g @apidevtools/swagger-cli
          npm install -g @openapitools/openapi-generator-cli

      - name: Check OpenAPI version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/OAI/OpenAPI-Specification/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/^v//')
          CURRENT_VERSION=$(grep "^openapi:" ./openapi/openapi.yml | awk '{print $2}')
          echo "Current OpenAPI version: $CURRENT_VERSION"
          echo "Latest OpenAPI version: $LATEST_VERSION"
          if [[ "$CURRENT_VERSION" != "$LATEST_VERSION" ]]; then
            echo "::warning file=openapi/openapi.yml,title=OpenAPI Version::Your OpenAPI specification is using version $CURRENT_VERSION while version $LATEST_VERSION is available. Consider upgrading to get the latest features and improvements."
          fi

      - name: Bundle OpenAPI files
        run: swagger-cli bundle ./openapi/openapi.yml --outfile ./openapi/_bundled.yml --type yaml

      - name: Validate OpenAPI specification
        run: swagger-cli validate ./openapi/_bundled.yml

      - name: Lint OpenAPI specification
        run: |
          npm install -g @stoplight/spectral-cli
          spectral lint --ruleset ./spectral.yaml --fail-severity=warn -f github-actions ./openapi/_bundled.yml

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Check for breaking API changes
        run: |
          set -e
          curl -sSL -o openapi-diff.jar \
            https://repo1.maven.org/maven2/org/openapitools/openapidiff/openapi-diff-cli/2.1.0/openapi-diff-cli-2.1.0-all.jar
          git fetch origin main
          git show origin/main:openapi/openapi.yml > ./openapi/previous.yml
          swagger-cli bundle ./openapi/previous.yml --outfile ./openapi/previous_bundled.yml --type yaml
          java -jar openapi-diff.jar --fail-on-incompatible ./openapi/previous_bundled.yml ./openapi/_bundled.yml
          rm -f ./openapi/previous.yml ./openapi/previous_bundled.yml openapi-diff.jar
